ALTER TABLE categories
DROP
CONSTRAINT categories_parent_id_fkey;

CREATE TABLE categorii
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nume      VARCHAR(255),
    parent_id BIGINT,
    CONSTRAINT pk_categorii PRIMARY KEY (id)
);

ALTER TABLE categorii
    ADD CONSTRAINT FK_CATEGORII_ON_PARENT FOREIGN KEY (parent_id) REFERENCES categorii (id);

DROP TABLE categories CASCADE;

DROP TABLE spatial_ref_sys CASCADE;