ALTER TABLE families ADD COLUMN IF NOT EXISTS created_at DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at DATE;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT FALSE;