package com.proiect.service;

import com.proiect.model.ChartFilters;
import com.proiect.model.ChartQueryIntent;
import com.proiect.model.ChartQueryResult;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

@JdbcTest
@Import(ChartQueryExecutor.class)
@ActiveProfiles("test")
@Transactional
class ChartQueryExecutorTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private ChartQueryExecutor chartQueryExecutor;

    @BeforeEach
    void setUp() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS expenses (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                amount DECIMAL(19,2) NOT NULL,
                category VARCHAR(255),
                person VARCHAR(255),
                location VARCHAR(255),
                date DATE,
                raw_input VARCHAR(1000),
                created_at TIMESTAMP
            )
            """);
    }

    private void insertExpense(BigDecimal amount, String category, String person, String location, LocalDate date) {
        jdbcTemplate.update(
                "INSERT INTO expenses (amount, category, person, location, date, raw_input, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
                amount, category, person, location, date, "test", LocalDateTime.now()
        );
    }

    @Test
    void testComparePersons() {
        insertExpense(new BigDecimal("100"), "mancare", "Teodor", "Lidl", LocalDate.of(2024, 1, 15));
        insertExpense(new BigDecimal("200"), "mancare", "Maria", "Lidl", LocalDate.of(2024, 1, 20));
        insertExpense(new BigDecimal("50"), "transport", "Teodor", "Metro", LocalDate.of(2024, 2, 10));

        ChartQueryIntent intent = ChartQueryIntent.builder()
                .responseType("chart")
                .chartType("bar")
                .aggregation("sum")
                .groupBy("person")
                .seriesBy(null)
                .title("Pe persoane")
                .filters(ChartFilters.builder().build())
                .build();

        ChartQueryResult result = chartQueryExecutor.execute(intent, null, null);

        assertEquals(2, result.getRows().size());
        assertEquals(List.of("value"), result.getSeriesNames());

        Map<String, Object> teodorRow = result.getRows().stream()
                .filter(r -> "Teodor".equals(r.get("name"))).findFirst().orElseThrow();
        assertEquals(0, ((BigDecimal) teodorRow.get("value")).compareTo(new BigDecimal("150")));
    }

    @Test
    void testCategoryBreakdown() {
        insertExpense(new BigDecimal("100"), "mancare", "Teodor", "Lidl", LocalDate.of(2024, 1, 15));
        insertExpense(new BigDecimal("200"), "mancare", "Maria", "Lidl", LocalDate.of(2024, 1, 20));
        insertExpense(new BigDecimal("50"), "transport", "Teodor", "Metro", LocalDate.of(2024, 2, 10));

        ChartQueryIntent intent = ChartQueryIntent.builder()
                .responseType("chart")
                .chartType("pie")
                .aggregation("sum")
                .groupBy("category")
                .seriesBy(null)
                .title("Pe categorii")
                .filters(ChartFilters.builder().build())
                .build();

        ChartQueryResult result = chartQueryExecutor.execute(intent, null, null);

        assertEquals(2, result.getRows().size());

        Map<String, Object> mancareRow = result.getRows().stream()
                .filter(r -> "mancare".equals(r.get("name"))).findFirst().orElseThrow();
        assertEquals(0, ((BigDecimal) mancareRow.get("value")).compareTo(new BigDecimal("300")));
    }

    @Test
    void testMonthlyTrend() {
        insertExpense(new BigDecimal("100"), "mancare", "Teodor", "Lidl", LocalDate.of(2024, 1, 15));
        insertExpense(new BigDecimal("200"), "mancare", "Maria", "Lidl", LocalDate.of(2024, 1, 20));
        insertExpense(new BigDecimal("150"), "mancare", "Teodor", "Lidl", LocalDate.of(2024, 2, 10));
        insertExpense(new BigDecimal("50"), "mancare", "Maria", "Lidl", LocalDate.of(2024, 2, 15));

        ChartQueryIntent intent = ChartQueryIntent.builder()
                .responseType("chart")
                .chartType("line")
                .aggregation("sum")
                .groupBy("month")
                .seriesBy("person")
                .title("Evoluție lunară")
                .filters(ChartFilters.builder().build())
                .build();

        ChartQueryResult result = chartQueryExecutor.execute(intent, null, null);

        assertEquals(2, result.getSeriesNames().size());
        assertTrue(result.getSeriesNames().contains("Teodor"));
        assertTrue(result.getSeriesNames().contains("Maria"));
        assertEquals(2, result.getRows().size());

        Map<String, Object> janRow = result.getRows().stream()
                .filter(r -> "2024-01".equals(r.get("name"))).findFirst().orElseThrow();
        assertEquals(0, ((BigDecimal) janRow.get("Teodor")).compareTo(new BigDecimal("100")));
        assertEquals(0, ((BigDecimal) janRow.get("Maria")).compareTo(new BigDecimal("200")));
    }

    @Test
    void testWithCategoryFilter() {
        insertExpense(new BigDecimal("100"), "mancare", "Teodor", "Lidl", LocalDate.of(2024, 1, 15));
        insertExpense(new BigDecimal("200"), "shopping", "Teodor", "Mall", LocalDate.of(2024, 1, 20));

        ChartQueryIntent intent = ChartQueryIntent.builder()
                .responseType("chart")
                .chartType("bar")
                .aggregation("sum")
                .groupBy("person")
                .seriesBy(null)
                .title("Filtrat")
                .filters(ChartFilters.builder().category("mancare").build())
                .build();

        ChartQueryResult result = chartQueryExecutor.execute(intent, List.of("mancare"), null);

        assertEquals(1, result.getRows().size());
        assertEquals(0, ((BigDecimal) result.getRows().get(0).get("value")).compareTo(new BigDecimal("100")));
    }

    @Test
    void testInvalidGroupByThrowsException() {
        ChartQueryIntent intent = ChartQueryIntent.builder()
                .responseType("chart")
                .aggregation("sum")
                .groupBy("invalid_column")
                .build();

        assertThrows(IllegalArgumentException.class, () ->
                chartQueryExecutor.execute(intent, null, null));
    }

    @Test
    void testEmptyResult() {
        ChartQueryIntent intent = ChartQueryIntent.builder()
                .responseType("chart")
                .chartType("bar")
                .aggregation("sum")
                .groupBy("person")
                .seriesBy(null)
                .title("Gol")
                .filters(ChartFilters.builder().build())
                .build();

        ChartQueryResult result = chartQueryExecutor.execute(intent, null, null);

        assertTrue(result.getRows().isEmpty());
    }
}
