spring.application.name=cheltuieli-familie

# Configurații bază de date - A se completa în application-local.properties sau prin variabile de mediu
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/familie_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# OCR
tesseract.datapath=${TESSERACT_DATAPATH:/usr/share/tesseract-ocr/5/tessdata/}

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=18
spring.flyway.locations=classpath:db/migration, classpath:db/postgres

# JPA
spring.jpa.show-sql=false

# Monitoring
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true

# Swagger / OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.packages-to-scan=com.familie.cheltuieli_familie

server.port=8081
