spring:
  datasource:
    url: jdbc:postgresql://db:5432/main_db
    username: FamilyDB
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

qdrant:
  host: qdrant
  port: 6334
  collection-name: expenses

# LangChain4j Config referencing .env values
langchain4j:
  open-ai:
    chat-model:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com/v1
      model-name: deepseek-chat
  open-router:
    chat-model:
      api-key: ${OPENROUTER_API_KEY}
      base-url: https://openrouter.ai/api/v1
      model-name: nvidia/nemotron-4-340b-instruct
    embedding-model:
      api-key: ${OPENROUTER_API_KEY}
      base-url: https://openrouter.ai/api/v1
      model-name: nvidia/llama-nemotron-embed-vl-1b-v2:free
