
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS expense_date TIMESTAMP;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS currency VARCHAR(10) DEFAULT 'RON';
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS source_type VARCHAR(20) DEFAULT 'manual';
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;


UPDATE expenses SET expense_date = created_at WHERE expense_date IS NULL;


ALTER TABLE expense_items ADD COLUMN IF NOT EXISTS item_name VARCHAR(255);
ALTER TABLE expense_items ADD COLUMN IF NOT EXISTS quantity DECIMAL(19, 2) DEFAULT 1;
ALTER TABLE expense_items ADD COLUMN IF NOT EXISTS raw_text TEXT;
ALTER TABLE expense_items ADD COLUMN IF NOT EXISTS category_id BIGINT;